training: !!bool 'false' #"true"
device: 'cpu' # "cuda"
unprocessed_data: './TIMIT/*/*/*/*.wav'
---
data:
    train_path: './data/'
    train_path_unprocessed: './TIMIT/TRAIN/*/*/*.wav'
    test_path: './data/'
    test_path_unprocessed: './TIMIT/TEST/*/*/*.wav'
    data_preprocessed: !!bool "true"
    sr: 16000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 23 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---
model:
    hidden: 64 # 768 #Number of LSTM hidden layer units
    num_layer: 1 # 3 #Number of LSTM layers
    proj: 32 # 256 #Embedding size
    model_path: './speech_id_checkpoint/model.model' #Model path for testing, inference, or resuming training
---
train:
    N : 2 # 4 #Number of speakers in batch
    M : 2 # 5 #Number of utterances per speaker
    num_workers: 0 #number of workers for dataloader
    lr: 0.01
    epochs: 950 #Max training speaker epoch
    log_interval: 1 #Epochs before printing progress
    log_file: './speech_id_checkpoint/Stats'
    checkpoint_interval: 120 #Save model after x speaker epochs
    checkpoint_dir: './speech_id_checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 2 # 4 #Number of speakers in batch
    M : 2 # 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
