training: !!bool 'true' #"true"
device: 'cpu' # "cuda"
unprocessed_data: './TIMIT/*/*/*/*.wav'
---
data:
    train_path: '/home/vano/wrkdir/projects_data/sre_2019/toy_dataset/'
    test_path: '/home/vano/wrkdir/projects_data/sre_2019/toy_dataset/'
    eval_path: '/home/vano/wrkdir/projects_data/sre_2019/toy_dataset/'
    data_preprocessed: !!bool "true"
    sr: 8000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 64 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---
model:
    hidden: 64 # 768 #Number of LSTM hidden layer units
    num_layer: 1 # 3 #Number of LSTM layers
    proj: 32 # 256 #Embedding size
    model_path: './checkpoint/final_epoch_20_batch_id_5.model' #Model path for testing, inference, or resuming training
---
train:
    N : 2 # 4 #Number of speakers in batch
    M : 2 # 5 #Number of utterances per speaker
    num_workers: 4 #number of workers for dataloader
    lr: 0.01
    epochs: 20 #Max training speaker epoch
    log_interval: 1 #Epochs before printing progress
    log_file: './checkpoint/Stats'
    checkpoint_interval: 10 #Save model after x speaker epochs
    checkpoint_dir: './checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 5 # 4 #Number of speakers in batch
    M : 2 # 6 #Number of utterances per speaker
    num_workers: 0 #number of workers for data laoder
    epochs: 1 #testing speaker epochs
