training: !!bool "true"
device: "cuda:0"
unprocessed_data: './TIMIT/*/*/*/*.wav'
---
data:
    train_path: '/home/vano/wrkdir/projects_data/sre_2019/swbd_sre_small_fbank/'
    test_path: '/home/vano/wrkdir/projects_data/sre_2019/swbd_sre_small_fbank/'
    data_preprocessed: !!bool "true"
    sr: 8000
    nfft: 512 #For mel spectrogram preprocess
    window: 0.025 #(s)
    hop: 0.01 #(s)
    nmels: 64 #Number of mel energies
    tisv_frame: 180 #Max number of time steps in input after preprocess
---   
model:
    hidden: 768 # 768 #Number of LSTM hidden layer units
    num_layer: 3 # 3 #Number of LSTM layers
    proj: 256 # 256 #Embedding size
    model_path: './model.model' #Model path for testing, inference, or resuming training
---
train:
    N : 16 #4 #Number of speakers in batch
    M : 8 # 5 #Number of utterances per speaker
    num_workers: 8 #number of workers for dataloader
    lr: 0.01 
    epochs: 100 #Max training speaker epoch
    log_interval: 15 #Epochs before printing progress
    log_file: './checkpoint/Stats'
    checkpoint_interval: 2 #Save model after x speaker epochs
    checkpoint_dir: './checkpoint'
    restore: !!bool "false" #Resume training from previous model path
---
test:
    N : 4 #Number of speakers in batch
    M : 6 #Number of utterances per speaker
    num_workers: 8 #number of workers for data laoder
    epochs: 10 #testing speaker epochs
